image: docker:stable

services:
- docker:dind

variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  USERNAME: "antmounds"
  IMAGE_NAME: "antennae"
  DOCKERHUB_IMAGE_NAME: ${USERNAME}/${IMAGE_NAME}
  GITLAB_IMAGE_NAME: ${USERNAME}/${IMAGE_NAME}

stages:
  - build
  - tag
  - push
  - deploy

build:
  stage: build
  script: 
    - echo "Building the app"
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --rm --cache-from $CI_REGISTRY_IMAGE:latest -t $IMAGE_NAME --build-arg BUILD=$CI_PIPELINE_IID .

tag_dockerhub:
  stage: tag
  script:
    - docker tag $IMAGE_NAME $DOCKERHUB_IMAGE_NAME:latest
    - docker tag $IMAGE_NAME $DOCKERHUB_IMAGE_NAME:$CI_PIPELINE_IID
  only:
  - master

tag_gitlab:
  stage: tag
  script: |
    docker tag $IMAGE_NAME $CI_REGISTRY_IMAGE:latest
    docker tag $IMAGE_NAME $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID

push_dockerhub:
  image: docker:stable
  stage: push
  script: |
    docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
    docker push $IMAGE_NAME
  only:
  - master

push_gitlab:
  image: docker:stable
  stage: push
  script: |
    docker login registry.gitlab.com
    docker push $IMAGE_NAME




deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
  - master
