stages:
  - test
  - build
  - deploy

test:
  image: ubuntu
  stage: test
  script: echo "Running tests";ls -lha;export;

build:
  image: docker:stable-git
  # variables:
  #   CI_DEBUG_TRACE: "true"
  stage: build
  script: 
    - echo "Building the app"
    - export

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
  - master
