# Antennae GitLab configuration
# 
.job_template: &job_build  # Hidden key that defines an anchor named 'job_build'
  image: docker:stable
  services:
    - docker:dind
  cache:
    untracked: true

variables:
  # When using dind, it's wise to use the overlayfs driver for improved performance.
  DOCKER_DRIVER: overlay2
  USERNAME: "antmounds"
  IMAGE_NAME: "antennae"
  DOCKERHUB_IMAGE_NAME: ${USERNAME}/${IMAGE_NAME}

stages:
  - build
  - deploy

build_push_gitlab:
  <<: *job_build
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script: 
    - echo "Building the app for Gitlab registry"
    - docker pull $CI_REGISTRY_IMAGE:dev || true
    - docker build --rm -f docker/Dockerfile --cache-from $CI_REGISTRY_IMAGE:dev -t $CI_REGISTRY_IMAGE --build-arg BUILD=$CI_PIPELINE_IID .
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE/dev:$CI_PIPELINE_IID
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE/dev/nick:$CI_PIPELINE_IID
    - docker push $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE/dev:$CI_PIPELINE_IID
    - docker push $CI_REGISTRY_IMAGE/dev/nick:$CI_PIPELINE_IID

build_push_dockerhub:
  <<: *job_build
  stage: build
  before_script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  script: 
    - echo "Building the app for Dockerhub registry"
    - docker pull $DOCKERHUB_IMAGE_NAME || true
    - docker build --rm -f docker/Dockerfile --cache-from $DOCKERHUB_IMAGE_NAME -t $DOCKERHUB_IMAGE_NAME --build-arg BUILD=$CI_PIPELINE_IID .
    - docker tag $DOCKERHUB_IMAGE_NAME $DOCKERHUB_IMAGE_NAME:$CI_PIPELINE_IID
    # - docker push $DOCKERHUB_IMAGE_NAME (wait till version # is >= CircleCI build_num)
  only:
  - master

deploy_dev:
  image: antmounds/cd-builder
  stage: deploy
  script: |
    aws --version
    docker --version
    docker-compose --version
    terraform --version
  environment:
    name: dev
    url: dev.getantennae.com
  except:
    - master

deploy_new:
  image: antmounds/cd-builder
  stage: deploy
  script: |
    terraform --version
    aws --version
  environment:
    name: staging
    url: new.getantennae.com
  only:
    - master

deploy_app:
  image: antmounds/cd-builder
  stage: deploy
  script: |
    terraform --version
    aws --version
  environment:
    name: production
    url: app.getantennae.com
  when: manual
  only:
    - master

deploy_infrastructure:
  image: antmounds/cd-builder
  stage: deploy
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: us-east-1
  script: |
    cd infrastructure/aws-ecs
    terraform init -backend=true -input=false -lock=true
    terraform show
    terraform plan -lock=true -refresh=true
    #terraform apply -lock=true -refresh=true -auto-approve -target=resource -var 'foo=bar'
    terraform --version
    aws --version
  environment:
    name: terraform
  when: manual