# Antennae CircleCI 2.0 configuration
# 
version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    #working_directory:
    environment:
      IMAGE_NAME: $CIRCLE_PROJECT_REPONAME:$(git log -1 --format=%h)
      DOCKERHUB_IMAGE_NAME: "${DOCKER_HUB_USERNAME}/${IMAGE_NAME}"
      AWS_IMAGE_NAME: "166964003196.dkr.ecr.us-east-1.amazonaws.com/${IMAGE_NAME}"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Build image
          command: |
            IMAGE_NAME=$CIRCLE_PROJECT_REPONAME:$(git log -1 --format=%h)
            docker build --rm -f Dockerfile-test -t $IMAGE_NAME --build-arg BUILD=$CIRCLE_BUILD_NUM --build-arg MONGO_URL=$MONGO_URL .
      - run:
          # tag Docker image for the Dockerhub registry
          name: Tag Dockerhub image
          command: docker tag $IMAGE_NAME $DOCKERHUB_IMAGE_NAME
      - run:
          # authenticate with the Docker Hub registry
          name: Dockerhub login
          command: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
      - run:
          # push the new Docker image to the Docker registry
          name: Dockerhub push
          command: docker push $DOCKERHUB_IMAGE_NAME
          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master