# Antennae CircleCI 2.0 configuration
# 
version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Build image
          command: |
            IMAGE_NAME=$CIRCLE_PROJECT_REPONAME
            docker build --rm -t $IMAGE_NAME --build-arg BUILD=$CIRCLE_BUILD_NUM --build-arg MONGO_URL=$MONGO_URL .
      - run:
          # tag Docker image for the Dockerhub registry
          name: Tag Dockerhub image
          command: |
            IMAGE_NAME=$CIRCLE_PROJECT_REPONAME
            DOCKERHUB_IMAGE_NAME=${DOCKER_HUB_USERNAME}/${IMAGE_NAME}
            docker tag $IMAGE_NAME $DOCKERHUB_IMAGE_NAME:latest
            docker tag $IMAGE_NAME $DOCKERHUB_IMAGE_NAME:$CIRCLE_BUILD_NUM
      - run:
          # authenticate with the Docker Hub registry
          name: Dockerhub login
          command: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
      - run:
          # push the new Docker image to the Docker registry
          name: Dockerhub push
          command: |
            IMAGE_NAME=$CIRCLE_PROJECT_REPONAME
            DOCKERHUB_IMAGE_NAME=${DOCKER_HUB_USERNAME}/${IMAGE_NAME}
            docker push $DOCKERHUB_IMAGE_NAME
          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master