FROM ubuntu

LABEL app="Antennae" license="GPLv3" maintainer="gitlab.com/Antmounds" repo="https://gitlab.com/Antmounds/Antennae" org.label-schema.build-date=$BUILD-DATE org.label-schema.name="Antennae" org.label-schema.description="Free, open-source, mobile-ready, face-recognition, check-in and loyalty app" org.label-schema.url="http://getAntennae.com" org.label-schema.vcs-url="https://gitlab.com/Antmounds/Antennae" org.label-schema.vendor="Antmounds" org.label-schema.version="0.9.0" org.label-schema.schema-version="1.0"

RUN apt-get update && apt-get install -y \
        apt-transport-https \
        apt-utils \
        aufs-tools \
        automake \
        build-essential \
        curl \
        git \
        lsb-release \
        sudo && \
    rm -rf /var/lib/apt/lists/* && \
    curl https://install.meteor.com/ | sh && \
	curl -sL https://deb.nodesource.com/setup_8.x | sh && \
	apt-get install -y nodejs && \  

    # Clean up stuff that's no longer needed
    apt-get autoremove -y && apt-get clean && \

    # Create user and add to sudoers
	useradd --create-home --shell /bin/bash nick && \
    echo 'nick ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    adduser nick sudo

USER nick

RUN mkdir /home/nick/app

WORKDIR /home/nick/app

COPY src ./src

WORKDIR /home/nick/app/src

RUN sudo chown -R nick /home/nick

RUN	sudo meteor npm install --save

EXPOSE 3000

CMD [ "meteor" ]